name2 = input("Номер тел/URL: ")
input("Прокси: ")
name = input("Сколько сообщений/ботов: ")
print("Атака началась!")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
print("Send " + str(name2) + " message/bot")
